version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db/migrations:/flyway/sql
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: admin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  flyway:
    depends_on:
      - db
    image: boxfuse/flyway
    volumes:
      - ./db/migrations:/flyway/sql
    command: ["-url=jdbc:mysql://db:3306/wordpress", "-user=wordpress", "-password=admin", "baseline", "migrate"]

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: admin
    volumes:
      - ./wordpress:/var/www/html

volumes:
  db_data: {}
